// 页面层：只负责渲染与交互，所有状态都来自 /api/state（规则层推算），刷新后一致。

const ITEM_FIELDS = [
  ["code", "墨锭编号", "text"],
  ["smokeSource", "烟料来源", "text"],
  ["glueRatio", "胶料比例", "text"],
  ["ageYears", "存放年限", "number"],
  ["storage", "存放位置", "text"],
];
const RECORD_KEYS = ["grinder", "mouth", "water", "paper", "temp", "humidity", "score"];
const RECORD_LABELS = {
  grinder: "试磨人",
  mouth: "磨口",
  water: "用水",
  paper: "纸样",
  temp: "室温",
  humidity: "湿度",
  score: "评分",
};
const RULES_TEXT = [
  "每锭墨锭同时只能有一个未结束批次；批次进行中不可再开新批次。",
  "登记结果须含磨口、用水、纸样、室温、湿度和试磨人；缺项则该批次作废且不占号，记录留档。",
  "连续两次高分（≥85）才放行；同一试磨人连续两次结果不能放行，须换人且间隔满 4 小时复核。",
  "任一低分（<85）重置连续高分计数，旧记录全部留档。",
  "更正关键字段会使已通过批次失效，更正前后内容留档。",
  "列表、批次履历与刷新后状态均由同一规则推算，始终一致。",
];

function css() {
  return [
    ":root{--bg:#f1f3ef;--panel:#fff;--ink:#20241f;--muted:#687066;--line:#d4ddd0;--accent:#526f43;--warn:#9b4937;--ok:#3c6e4f;}",
    "*{box-sizing:border-box;}body{margin:0;background:var(--bg);color:var(--ink);font-family:Arial,'PingFang SC',sans-serif;}",
    "header{padding:20px 28px;background:#fff;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:16px;align-items:center;}",
    "h1{margin:0;font-size:24px;}h2{margin:0 0 10px;font-size:17px;}h3{margin:0;font-size:15px;}",
    "main{display:grid;grid-template-columns:360px 1fr 1fr;gap:18px;padding:18px 28px;align-items:start;}",
    "form,.panel,.card,.stat{background:var(--panel);border:1px solid var(--line);border-radius:8px;padding:14px;}",
    "form{margin-bottom:14px;}",
    "label{display:block;margin:8px 0 4px;color:var(--muted);font-size:12px;}",
    "input,select,textarea{width:100%;border:1px solid var(--line);border-radius:6px;padding:8px;font:inherit;background:#fff;}",
    "button{border:0;border-radius:6px;background:var(--accent);color:#fff;padding:9px 12px;font-weight:700;cursor:pointer;}",
    "button.secondary{background:#69736a;}button.small{padding:5px 9px;font-size:12px;}",
    ".rules{list-style:none;margin:0;padding:0;font-size:12px;color:var(--muted);display:grid;gap:5px;}",
    ".rules li{padding-left:14px;position:relative;}.rules li::before{content:'◆';position:absolute;left:0;color:var(--accent);font-size:9px;top:3px;}",
    ".stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(110px,1fr));gap:10px;margin-bottom:12px;}",
    ".stat strong{display:block;font-size:22px;}.stat span{color:var(--muted);font-size:12px;}",
    ".toolbar{display:flex;gap:10px;flex-wrap:wrap;margin-bottom:12px;}.toolbar select,.toolbar input{width:auto;min-width:150px;}",
    ".grid{display:grid;gap:12px;}",
    ".card{display:grid;gap:8px;}",
    ".meta{color:var(--muted);font-size:12px;}",
    ".pill{display:inline-block;border:1px solid var(--line);border-radius:999px;padding:2px 8px;font-size:12px;}",
    ".pill.已放行{background:#e4efe3;border-color:#b9d2b6;color:var(--ok);}",
    ".pill.已作废,.pill.已失效,.pill.放行失效{background:#f3e4e0;border-color:#dfc0b6;color:var(--warn);}",
    ".pill.进行中,.pill.试磨中{background:#eef0e4;border-color:#ccd2b6;}",
    ".blockers{color:var(--warn);font-size:12px;margin:0;padding-left:16px;}",
    ".ok{color:var(--ok);font-weight:700;font-size:12px;}",
    ".warn{color:var(--warn);font-weight:700;}",
    "table.records{width:100%;border-collapse:collapse;font-size:12px;}",
    "table.records th,table.records td{border:1px solid var(--line);padding:4px 6px;text-align:left;vertical-align:top;}",
    "table.records th{background:#f4f6f1;color:var(--muted);font-weight:600;white-space:nowrap;}",
    "td.low{color:var(--warn);font-weight:700;}",
    "details.correct{border:1px dashed var(--line);border-radius:6px;padding:6px 8px;margin-top:4px;}",
    "details.correct summary{cursor:pointer;font-size:12px;color:var(--muted);}",
    "details.correct input{margin-bottom:4px;}",
    "details.correct label{margin:4px 0 2px;font-size:11px;}",
    "ol.history{margin:0;padding-left:18px;font-size:12px;display:grid;gap:3px;}",
    "ol.history .t{color:var(--muted);}",
    ".legacy{border-top:1px dashed var(--line);padding-top:6px;}",
    "#toast{position:fixed;right:18px;bottom:18px;background:#20241f;color:#fff;padding:10px 14px;border-radius:8px;font-size:13px;display:none;max-width:420px;}",
    "#toast.err{background:var(--warn);}",
    "@media(max-width:1100px){main{grid-template-columns:1fr;}header{display:block;}}",
  ].join("\n");
}

function clientJs() {
  return [
    "const ITEM_FIELDS = " + JSON.stringify(ITEM_FIELDS) + ";",
    "const RECORD_KEYS = " + JSON.stringify(RECORD_KEYS) + ";",
    "const RECORD_LABELS = " + JSON.stringify(RECORD_LABELS) + ";",
    "let state = { items: [], stats: {} };",
    "let expandedBatch = null;",
    "const $ = (s) => document.querySelector(s);",
    "const esc = (v) => String(v ?? '').replace(/[&<>\"']/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',\"'\":'&#39;' }[c]));",
    "const fmt = (iso) => iso ? new Date(iso).toLocaleString('zh-CN', { hour12: false }) : '—';",
    "function toast(msg, isErr) { const t = $('#toast'); t.textContent = msg; t.className = isErr ? 'err' : ''; t.style.display = 'block'; clearTimeout(t._h); t._h = setTimeout(() => t.style.display = 'none', 3200); }",
    "async function api(path, options) {",
    "  const res = await fetch(path, options && options.body ? Object.assign({}, options, { headers: { 'Content-Type': 'application/json' } }) : options);",
    "  const data = await res.json();",
    "  if (!res.ok) throw new Error(data.error || '请求失败');",
    "  return data;",
    "}",
    "async function run(fn) { try { await fn(); } catch (e) { toast(e.message, true); } }",
    "async function load() { state = await api('/api/state'); render(); }",
    "",
    "function renderForms() {",
    "  $('#itemFields').innerHTML = ITEM_FIELDS.map(([k, l, t]) => '<label>' + l + '</label><input name=\"' + k + '\" type=\"' + t + '\"' + (k === 'code' ? ' required' : '') + '>').join('');",
    "  $('#recordFields').innerHTML = RECORD_KEYS.map((k) => '<label>' + RECORD_LABELS[k] + '</label><input name=\"' + k + '\"' + (k === 'score' ? ' type=\"number\" min=\"0\" max=\"100\" step=\"1\"' : '') + '>').join('')",
    "    + '<label>登记时间（可选，留空取当前时间）</label><input name=\"at\" type=\"datetime-local\">';",
    "}",
    "",
    "function render() {",
    "  renderStats();",
    "  renderItems();",
    "  renderBoard();",
    "}",
    "",
    "function renderStats() {",
    "  $('#stats').innerHTML = Object.entries(state.stats).map(([k, v]) => '<div class=\"stat\"><span>' + esc(k) + '</span><strong>' + v + '</strong></div>').join('');",
    "}",
    "",
    "function renderItems() {",
    "  const q = $('#search').value.trim();",
    "  const status = $('#statusFilter').value;",
    "  const visible = state.items.filter((it) => (!status || it.status === status) && (!q || JSON.stringify(it).includes(q)));",
    "  $('#items').innerHTML = visible.map(itemCard).join('') || '<div class=\"meta\">没有符合条件的墨锭</div>';",
    "  document.querySelectorAll('[data-open]').forEach((btn) => btn.onclick = () => run(async () => {",
    "    await api('/api/items/' + btn.dataset.open + '/batches', { method: 'POST', body: '{}' });",
    "    toast('已开启新批次'); await load();",
    "  }));",
    "  document.querySelectorAll('[data-expand]').forEach((btn) => btn.onclick = () => { expandedBatch = expandedBatch === btn.dataset.expand ? null : btn.dataset.expand; renderBoard(); });",
    "}",
    "",
    "function itemCard(it) {",
    "  const open = it.batches.find((b) => b.state === '进行中');",
    "  const numbered = it.batches.filter((b) => b.batchNo);",
    "  const rows = numbered.slice().reverse().map((b) =>",
    "    '<div class=\"meta\">批次 #' + b.batchNo + ' · ' + b.state + ' · ' + b.records.length + ' 条结果 · ' + fmt(b.openedAt) + '</div>'",
    "  ).join('');",
    "  const legacy = (it.legacyLogs || []).map((l) => '<div class=\"meta\">' + esc(l.step) + '：' + esc(l.note) + '</div>').join('');",
    "  return '<article class=\"card\">'",
    "    + '<h3>' + esc(it.code) + ' <span class=\"pill ' + it.status + '\">' + it.status + '</span></h3>'",
    "    + '<div class=\"meta\">' + esc(it.smokeSource) + ' · 胶 ' + esc(it.glueRatio) + ' · ' + esc(it.ageYears) + ' 年 · ' + esc(it.storage) + '</div>'",
    "    + (open ? '<div class=\"meta\">进行中批次 #' + open.batchNo + '（未结束，不可开新批次）</div>'",
    "            : '<button class=\"small\" data-open=\"' + esc(it.id) + '\">开启新批次</button>')",
    "    + (rows ? '<div>' + rows + '</div>' : '<div class=\"meta\">暂无占号批次</div>')",
    "    + (legacy ? '<div class=\"legacy\">' + legacy + '</div>' : '')",
    "    + '</article>';",
    "}",
    "",
    "function renderBoard() {",
    "  const openBatches = [];",
    "  state.items.forEach((it) => it.batches.forEach((b) => { if (b.state === '进行中') openBatches.push({ it, b }); }));",
    "  const sel = $('#recordBatch');",
    "  const prev = sel.value;",
    "  sel.innerHTML = openBatches.map(({ it, b }) => '<option value=\"' + esc(it.id) + '|' + esc(b.id) + '\">' + esc(it.code) + ' · 批次 #' + b.batchNo + '</option>').join('');",
    "  if (prev) sel.value = prev;",
    "  $('#recordForm').style.display = openBatches.length ? '' : 'none';",
    "  $('#noOpen').style.display = openBatches.length ? 'none' : '';",
    "  $('#board').innerHTML = openBatches.map(({ it, b }) => batchCard(it, b)).join('') || '<div class=\"meta\">当前没有进行中的批次</div>';",
    "  bindBoard();",
    "}",
    "",
    "function batchCard(it, b) {",
    "  const rel = b.release;",
    "  const verdict = rel.releasable",
    "    ? '<div class=\"ok\">已满足放行条件，批次将自动放行</div>'",
    "    : '<ul class=\"blockers\">' + rel.blockers.map((x) => '<li>' + esc(x) + '</li>').join('') + '</ul>';",
    "  const streak = '<div class=\"meta\">连续高分计数：' + rel.streakCount + ' / 2（任一低分即重置）</div>';",
    "  const table = b.records.length ? recordTable(it, b) : '<div class=\"meta\">尚无登记结果</div>';",
    "  const history = '<ol class=\"history\">' + b.history.map((h) => '<li><span class=\"t\">' + fmt(h.at) + '</span> ' + esc(h.note) + '</li>').join('') + '</ol>';",
    "  const open = expandedBatch === b.id;",
    "  return '<article class=\"card\">'",
    "    + '<h3>' + esc(it.code) + ' · 批次 #' + b.batchNo + ' <span class=\"pill ' + b.state + '\">' + b.state + '</span></h3>'",
    "    + '<div class=\"meta\">开启于 ' + fmt(b.openedAt) + '</div>'",
    "    + streak + verdict + table",
    "    + '<button class=\"small secondary\" data-toggle=\"' + esc(b.id) + '\">' + (open ? '收起批次履历' : '展开批次履历') + '</button>'",
    "    + (open ? history : '')",
    "    + '</article>';",
    "}",
    "",
    "function recordTable(it, b) {",
    "  const head = '<tr><th>时间</th><th>试磨人</th><th>磨口</th><th>用水</th><th>纸样</th><th>室温</th><th>湿度</th><th>评分</th><th></th></tr>';",
    "  const rows = b.records.map((r) => {",
    "    const low = Number(r.score) < 85;",
    "    return '<tr><td>' + fmt(r.at) + '</td><td>' + esc(r.grinder) + '</td><td>' + esc(r.mouth) + '</td><td>' + esc(r.water) + '</td><td>' + esc(r.paper) + '</td><td>' + esc(r.temp) + '</td><td>' + esc(r.humidity) + '</td>'",
    "      + '<td class=\"' + (low ? 'low' : '') + '\">' + esc(r.score) + (low ? '（低分，计数重置）' : '') + '</td>'",
    "      + '<td><button class=\"small secondary\" data-correct=\"' + esc(it.id) + '|' + esc(b.id) + '|' + esc(r.id) + '\">更正</button></td></tr>'",
    "      + '<tr data-correct-row=\"' + esc(r.id) + '\" style=\"display:none\"><td colspan=\"9\">' + correctForm(it, b, r) + '</td></tr>';",
    "  }).join('');",
    "  return '<table class=\"records\">' + head + rows + '</table>';",
    "}",
    "",
    "function correctForm(it, b, r) {",
    "  const inputs = RECORD_KEYS.map((k) => '<label>' + RECORD_LABELS[k] + '</label><input name=\"' + k + '\" value=\"' + esc(r[k]) + '\"' + (k === 'score' ? ' type=\"number\" min=\"0\" max=\"100\" step=\"1\"' : '') + '>').join('');",
    "  return '<form data-correct-form=\"' + esc(it.id) + '|' + esc(b.id) + '|' + esc(r.id) + '\">'",
    "    + '<div class=\"meta\">更正关键字段会使已通过批次失效，更正前后内容留档。</div>'",
    "    + inputs + '<label>更正原因</label><input name=\"reason\" placeholder=\"必填\">'",
    "    + '<button class=\"small\">提交更正</button></form>';",
    "}",
    "",
    "function bindBoard() {",
    "  document.querySelectorAll('[data-toggle]').forEach((btn) => btn.onclick = () => { expandedBatch = expandedBatch === btn.dataset.toggle ? null : btn.dataset.toggle; renderBoard(); });",
    "  document.querySelectorAll('[data-correct]').forEach((btn) => btn.onclick = () => {",
    "    const row = document.querySelector('[data-correct-row=\"' + btn.dataset.correct.split('|')[2] + '\"]');",
    "    row.style.display = row.style.display === 'none' ? '' : 'none';",
    "  });",
    "  document.querySelectorAll('[data-correct-form]').forEach((form) => form.onsubmit = (e) => {",
    "    e.preventDefault();",
    "    const [itemId, batchId, recordId] = form.dataset.correctForm.split('|');",
    "    const data = Object.fromEntries(new FormData(form).entries());",
    "    run(async () => {",
    "      await api('/api/items/' + itemId + '/batches/' + batchId + '/records/' + recordId, { method: 'PATCH', body: JSON.stringify(data) });",
    "      toast('已更正并留档'); await load();",
    "    });",
    "  });",
    "}",
    "",
    "document.addEventListener('DOMContentLoaded', () => {",
    "  renderForms();",
    "  $('#itemForm').onsubmit = (e) => { e.preventDefault(); run(async () => {",
    "    await api('/api/items', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(e.target).entries())) });",
    "    e.target.reset(); toast('墨锭已建档'); await load();",
    "  }); };",
    "  $('#recordForm').onsubmit = (e) => { e.preventDefault(); run(async () => {",
    "    const [itemId, batchId] = $('#recordBatch').value.split('|');",
    "    const data = Object.fromEntries(new FormData(e.target).entries());",
    "    if (!data.at) delete data.at;",
    "    await api('/api/items/' + itemId + '/batches/' + batchId + '/records', { method: 'POST', body: JSON.stringify(data) });",
    "    e.target.reset(); toast('结果已登记'); await load();",
    "  }); };",
    "  $('#statusFilter').onchange = renderItems;",
    "  $('#search').oninput = renderItems;",
    "  $('#reload').onclick = () => run(load);",
    "  run(load);",
    "});",
  ].join("\n");
}

export function page() {
  const statusOptions = ["待试磨", "试磨中", "已放行", "放行失效"]
    .map((s) => "<option>" + s + "</option>")
    .join("");
  return [
    "<!doctype html>",
    '<html lang="zh-CN">',
    "<head>",
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1">',
    "<title>墨锭试磨室 · 试磨批次与放行台</title>",
    "<style>" + css() + "</style>",
    "</head>",
    "<body>",
    "<header><div><h1>墨锭试磨室 · 试磨批次与放行台</h1>",
    '<div class="meta">批次占号、缺项作废、换人复核、更正失效 —— 规则 / 存档 / 页面分层实现</div></div>',
    '<button id="reload">刷新</button></header>',
    "<main>",
    "<section>",
    '<form id="itemForm"><h2>墨锭建档</h2><div id="itemFields"></div><button>保存墨锭</button></form>',
    '<form id="recordForm"><h2>登记试磨结果</h2>',
    '<label>进行中批次</label><select id="recordBatch"></select>',
    '<div id="recordFields"></div>',
    "<button>提交登记</button></form>",
    '<div class="panel" id="noOpen" style="display:none"><div class="meta">当前没有进行中的批次，请先在墨锭列表开启批次。</div></div>',
    '<div class="panel"><h2>放行规则</h2><ul class="rules">',
    RULES_TEXT.map((t) => "<li>" + t + "</li>").join(""),
    "</ul></div>",
    "</section>",
    "<section>",
    '<div class="stats" id="stats"></div>',
    '<div class="toolbar"><select id="statusFilter"><option value="">全部状态</option>' + statusOptions + "</select>",
    '<input id="search" placeholder="搜索编号或关键词"></div>',
    '<div class="grid" id="items"></div>',
    "</section>",
    "<section>",
    '<div class="panel" style="margin-bottom:12px"><h2>放行台</h2>',
    '<div class="meta">仅展示进行中的批次；满足条件自动放行，缺项登记将作废该批次且不占号。</div></div>',
    '<div class="grid" id="board"></div>',
    "</section>",
    "</main>",
    '<div id="toast"></div>',
    "<script>" + clientJs() + "</script>",
    "</body>",
    "</html>",
  ].join("\n");
}
